# Generated by Django 5.2 on 2025-04-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
