# Generated by Django 5.2 on 2025-04-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_data', '0003_character_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='subjectNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('NB', 'Non-binary'), ('OTHER', 'Other'), ('FEMISH', 'Feminine-aligned'), ('MASCISH', 'Masculine-aligned')], null=True),
        ),
    ]
