# Generated by Django 5.2 on 2025-04-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_data', '0004_character_subjectnumber_alter_character_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='specificRole',
            field=models.CharField(choices=[('DOCILE', 'Docile'), ('LAHDE', 'Lahde'), ('CRONUS', 'Cronus'), ('HALCYON', 'Halcyon'), ('NONVIABLE', 'Nonviable'), ('SCIENTIST', 'Scientist'), ('MEDSTAFF', 'Medical Staff'), ('INTERN', 'Intern')], null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='role',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('SUBJECT', 'Subject')], null=True),
        ),
    ]
