# Generated by Django 5.2 on 2025-05-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_data', '0005_character_specificrole_alter_character_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='allosexual',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='orientation',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='species',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Non-binary', 'Non-binary'), ('Other', 'Other'), ('Feminine-aligned', 'Feminine-aligned'), ('Masculine-aligned', 'Masculine-aligned')], null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='role',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Subject', 'Subject')], null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='specificRole',
            field=models.CharField(choices=[('Docile', 'Docile'), ('Lahde', 'Lahde'), ('Cronus', 'Cronus'), ('Halcyon', 'Halcyon'), ('Nonviable', 'Nonviable'), ('Scientist', 'Scientist'), ('Medical Staff', 'Medical Staff'), ('Intern', 'Intern')], null=True),
        ),
    ]
