# Generated by Django 5.1.3 on 2025-07-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character_data", "0007_alter_character_age_alter_character_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="submitted",
            field=models.BooleanField(null=True),
        ),
    ]
