# Generated by Django 5.1.3 on 2025-07-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character_data", "0008_character_submitted"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="documentLink",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
