# Generated by Django 5.1.3 on 2025-07-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character_data", "0009_character_documentlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="muse",
            field=models.IntegerField(
                choices=[
                    (1, "Red"),
                    (2, "Orange"),
                    (3, "Yellow"),
                    (4, "Green"),
                    (5, "Blue"),
                ],
                null=True,
            ),
        ),
    ]
